### ISSUE TITLE
Flask web app

### ISSUE THREAD

**Issue by zhidelev** [zhidelev/delicious_bookmarks#27]
# Prerequisites 

- [x] https://www.youtube.com/watch?v=nrzLdMWTRMM
- [ ] https://testdriven.io/blog/django-vs-flask/
- [ ] https://realpython.com/flask-connexion-rest-api/
- [ ] https://realpython.com/flask-connexion-rest-api-part-2/
- [ ] https://12factor.net/
- [ ] Load balancer: HAProxy
- [ ] Service registry: Etcd
- [ ] Confd (http://www.confd.io) - load balancer configuration
- [ ] Docker
- [ ] Logspout ( logging)
- [ ] MySQL
- [ ] Redis message queue
- [ ] JWT

# TO-DO
